### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by profshor** [yandex-money/yandex-money-sdk-java#1]
How to perform authorization?
How to obtain temporary token, what should be in constant ApiTest.ACCESS_TOKEN ?
Can be aded a test performing authorization with/without client_secret?

**Comment by yasevich** [comment]
Authorization request described on [this page](https://tech.yandex.com/money/doc/dg/reference/request-access-token-docpage/).

Constant ```ApiTest.ACCESS_TOKEN``` should have access token strangly enough. =) Please read [this page](https://tech.yandex.com/money/doc/dg/reference/obtain-access-token-docpage/).

```client_secret``` is not required. But it is highly recommended to use it on production.

Please, refer to [documentation](https://tech.yandex.com/money/doc/dg/concepts/About-docpage/) to find answers on your questions. If you need a clarification on any of them feel free to contact our [support](mailto:support@money.yandex.ru).
