### ISSUE TITLE
Test for p2p payment to another wallet

### ISSUE THREAD

**Issue by profshor** [yandex-money/yandex-money-sdk-java#2]
Please add test for payment to another Yandex.Money wallet. 
Here is my parameters, fetched from debug print:
amount=1.00&comment=zzzzzzzzzz&to=41001649634926&test_payment=true&message=zzzzzzzzz&pattern_id=p2p
Response always is: status=REFUSED, error=ILLEGAL_PARAMS
What can be a problem, please?

**Comment by yasevich** [comment]
If you're making a test payment you must provide ```test_result``` parameter as well.
