### ISSUE TITLE
Third-Party Dependencies

### ISSUE THREAD

**Issue by kosik** [yandex-money/yandex-money-sdk-java#3]
Было-бы разумно не включать в клиентскую библиотеку таких зависимостей как GSON, joda-time и okhttp. 

1)Начиная с java8 аналогичная joda-time имплементация включена в стандартный JDK. Причём, похоже на то, что в этой реализации участвовали даже некоторые разработчики из команды joda-time.

2) Работа с сериализацией JSON возможна по средствам Java Beans. Если по-каким-то причинам вам не подходят стандартные механизмы или нет времени/других ресурсов на парсинг, то обычно такие вещи выносятся за рамки клиентской библиотеки и выставляют наружу интерфейс, принимающий исходниые данные. 

3) Не могу сказать какой из фреймворков okhttp или http://hc.apache.org/ является наиболее часто используемым для трансфера данных, но ни одна из трёх зависимостей что вы включили в обязательные не используется в моём проекте. По-моему более разумно для клиентской библиотеки было-бы следовать паттерну проектирования Facade и реализовать внутренюю инфраструктуру таким образом, чтобы предоставить клиентам возможность выбора провайдера. Либо вовсе реализовать подобные вещи на стандартном JDK.

Да, вы используете для сборки только Gradle. Почему не maven? Есть ли в планах дальнейшая работа над API?(roadmap)

**Comment by romkavt** [comment]
Спасибо за комментарии и интерес у нашему продукту :-)
По вашим комментариям:
1) мы проверим, попробуем что-нибудь сделать. Однако следует учесть что SDK используют также и пользователи Java7 и платформы Android, где joda-time в стандартной поставке нет.

2) и 3) мы считаем что реализация подобного интерфейса только усложнит использование SDK, так как на клиентской стороне дополнительно необходимо будет реализовывать промежуточный слой между интерфейсами SDK и локальным HTTP клиентом. SDK использует асинхронный механизм работы с HTTP, для которого стандартных интерфейсов Java сейчас нет.
Наше SDK также используется и на мобильных платформах, где использование технологий JavaBeans затруднительно.

>> Да, вы используете для сборки только Gradle. Почему не maven?
Мы считаем Gradle наиболее подходящим инструментом для разработки наших продуктов.
Вы можете использовать maven в своем проекте, включив SDK как зависимость из jcenter/maven central.

>> Есть ли в планах дальнейшая работа над API?
да, конечно.
В первую очередь мы будем развивать мобильные платформы, но также поддерживать и server2server решения.

**Comment by kosik** [comment]
https://odrive.info/content/27_Paypal-traps-Yandex-Money-red-tape-Conservative-Google-Wallet
